# Autogenerated wrapper script for OMPEval_jll for x86_64-w64-mingw32
export libOMPEval

JLLWrappers.@generate_wrapper_header("OMPEval")
JLLWrappers.@declare_library_product(libOMPEval, "libOMPEval.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libOMPEval,
        "bin\\libOMPEval.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
